export type Category = {
  id: string;
  name: string;
  icon: string;
  color: string;
  bgColor: string;
  sortOrder: number;
};

export type Business = {
  id: string;
  name: string;
  categoryId: string;
  description: string;
  phone: string;
  email: string;
  website?: string;
  address: string;
  initials: string;
  boosted: boolean;
  featured: boolean;
  rating: number;
  reviewCount: number;
};

// Keep static data for SQL seed generation reference and local fallback
export const staticCategories: Category[] = [
  { id: "bygg", name: "Bygg & Hantverk", icon: "Hammer", color: "#C2410C", bgColor: "#FFF7ED", sortOrder: 1 },
  { id: "restaurang", name: "Restaurang & Café", icon: "UtensilsCrossed", color: "#0369A1", bgColor: "#F0F9FF", sortOrder: 2 },
  { id: "skonhet", name: "Skönhet & Hälsa", icon: "Sparkles", color: "#7C3AED", bgColor: "#F5F3FF", sortOrder: 3 },
  { id: "butiker", name: "Butiker", icon: "ShoppingBag", color: "#0F766E", bgColor: "#F0FDFA", sortOrder: 4 },
  { id: "transport", name: "Transport", icon: "Truck", color: "#1D4ED8", bgColor: "#EFF6FF", sortOrder: 5 },
  { id: "it", name: "IT & Teknik", icon: "Monitor", color: "#374151", bgColor: "#F9FAFB", sortOrder: 6 },
  { id: "fastighet", name: "Fastighet", icon: "Home", color: "#B45309", bgColor: "#FFFBEB", sortOrder: 7 },
  { id: "turism", name: "Turism & Upplevelser", icon: "Map", color: "#047857", bgColor: "#ECFDF5", sortOrder: 8 },
];

export const staticBusinesses: Business[] = [
  {
    id: "1",
    name: "Tanums Bygg & Snickeri",
    categoryId: "bygg",
    description: "Familjeföretag med 30 års erfarenhet av nybyggnation, renovering och allt inom snickeri på Sotenäs och i Tanum.",
    phone: "0525-123 45",
    email: "info@tanumsbygg.se",
    website: "www.tanumsbygg.se",
    address: "Industrivägen 4, Tanumshede",
    initials: "TB",
    boosted: true,
    featured: false,
    rating: 4.8,
    reviewCount: 47,
  },
  {
    id: "2",
    name: "Fjällbacka Måleri",
    categoryId: "bygg",
    description: "Professionell målarmästare med certifierade hantverkare. Vi utför alla typer av målningsarbeten, invändigt och utvändigt.",
    phone: "0525-456 78",
    email: "hej@fjallbackamaleri.se",
    address: "Strandvägen 12, Fjällbacka",
    initials: "FM",
    boosted: false,
    featured: false,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: "3",
    name: "Grebbestad VVS",
    categoryId: "bygg",
    description: "Din lokala rörmokare för installation, service och reparation av värme, vatten och sanitet.",
    phone: "0525-789 01",
    email: "kontakt@grebbevvs.se",
    website: "www.grebbevvs.se",
    address: "Hamnvägen 3, Grebbestad",
    initials: "GV",
    boosted: false,
    featured: false,
    rating: 4.6,
    reviewCount: 22,
  },
  {
    id: "4",
    name: "Hamburgsund El AB",
    categoryId: "bygg",
    description: "Behörig elinstallatör för alla slags elarbeten i bostad, fritidshus och företag.",
    phone: "0525-321 00",
    email: "info@hamburgsel.se",
    address: "Norra Hamnen 7, Hamburgsund",
    initials: "HE",
    boosted: false,
    featured: false,
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: "5",
    name: "Koster Mark & Anläggning",
    categoryId: "bygg",
    description: "Markarbeten, dränering, sprängning och asfaltering.",
    phone: "0525-654 32",
    email: "projekt@kostermark.se",
    address: "Kostervägen 18, Strömstad",
    initials: "KM",
    boosted: false,
    featured: false,
    rating: 4.5,
    reviewCount: 14,
  },
  {
    id: "6",
    name: "Café Havsbris",
    categoryId: "restaurang",
    description: "Mysigt hamnkafé med husmanskost, nybakat bröd och utsikt över Grebbestad. Öppet maj–september.",
    phone: "0525-112 23",
    email: "info@cafehavsbris.se",
    website: "www.cafehavsbris.se",
    address: "Kajen 1, Grebbestad",
    initials: "CH",
    boosted: true,
    featured: false,
    rating: 4.9,
    reviewCount: 124,
  },
  {
    id: "7",
    name: "Fjällbacka Krog",
    categoryId: "restaurang",
    description: "Klassisk krog i hjärtat av Fjällbacka. Säsongsmenyer med lokalt fångad fisk.",
    phone: "0525-334 55",
    email: "boka@fjallbackakrog.se",
    website: "www.fjallbackakrog.se",
    address: "Ingrid Bergmans torg 4, Fjällbacka",
    initials: "FK",
    boosted: false,
    featured: false,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "8",
    name: "Tanums Pizzeria",
    categoryId: "restaurang",
    description: "Hemgjord pizza, pasta och sallader. Takeaway och leverans i Tanumshede.",
    phone: "0525-445 67",
    email: "order@tanumspizzeria.se",
    address: "Affärsvägen 5, Tanumshede",
    initials: "TP",
    boosted: false,
    featured: false,
    rating: 4.3,
    reviewCount: 56,
  },
  {
    id: "9",
    name: "Smak av Bohuslän",
    categoryId: "restaurang",
    description: "Delikatessbutik och bistro med fokus på lokala producenter.",
    phone: "0525-556 78",
    email: "info@smakavbohuslan.se",
    address: "Storgatan 2, Tanumshede",
    initials: "SB",
    boosted: false,
    featured: false,
    rating: 4.8,
    reviewCount: 43,
  },
  {
    id: "10",
    name: "Hälsostudio Tanum",
    categoryId: "skonhet",
    description: "Gym, yoga och personlig träning.",
    phone: "0525-667 89",
    email: "traning@halsosdiotanum.se",
    website: "www.halsosdiotanum.se",
    address: "Södervägen 9, Tanumshede",
    initials: "HT",
    boosted: false,
    featured: false,
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: "11",
    name: "Salong Ingela",
    categoryId: "skonhet",
    description: "Välkommen till en klassisk damfrisör med moderna tekniker.",
    phone: "0525-778 90",
    email: "boka@salongingela.se",
    address: "Storgatan 14, Tanumshede",
    initials: "SI",
    boosted: true,
    featured: false,
    rating: 4.9,
    reviewCount: 72,
  },
  {
    id: "12",
    name: "Kusthälsan Massage",
    categoryId: "skonhet",
    description: "Medicinsk massage, zonterapi och akupunktur.",
    phone: "0525-889 01",
    email: "tid@kusthalsam.se",
    website: "www.kusthalsam.se",
    address: "Hälsovägen 2, Grebbestad",
    initials: "KH",
    boosted: false,
    featured: false,
    rating: 4.8,
    reviewCount: 29,
  },
  {
    id: "13",
    name: "Bohushandel",
    categoryId: "butiker",
    description: "Välsorterad järnhandel och byggvarubutik.",
    phone: "0525-990 12",
    email: "info@bohushandel.se",
    address: "Industrivägen 1, Tanumshede",
    initials: "BH",
    boosted: false,
    featured: false,
    rating: 4.4,
    reviewCount: 61,
  },
  {
    id: "14",
    name: "Kustboden",
    categoryId: "butiker",
    description: "Inredning, presenter och lokala hantverk.",
    phone: "0525-101 23",
    email: "hej@kustboden.se",
    website: "www.kustboden.se",
    address: "Kajen 5, Fjällbacka",
    initials: "KB",
    boosted: false,
    featured: false,
    rating: 4.8,
    reviewCount: 34,
  },
  {
    id: "15",
    name: "Tanum Sport & Fritid",
    categoryId: "butiker",
    description: "Sportbutik med allt för friluftsliv, havet och vintern.",
    phone: "0525-213 45",
    email: "sport@tanumsport.se",
    address: "Storgatan 8, Tanumshede",
    initials: "TS",
    boosted: false,
    featured: false,
    rating: 4.5,
    reviewCount: 27,
  },
  {
    id: "16",
    name: "Bohus Transport",
    categoryId: "transport",
    description: "Lokal åkeri med containertransport och budservice.",
    phone: "0525-324 56",
    email: "jobb@bohustransport.se",
    address: "Hamnvägen 11, Hamburgsund",
    initials: "BT",
    boosted: false,
    featured: false,
    rating: 4.6,
    reviewCount: 19,
  },
  {
    id: "17",
    name: "Kusttaxi Tanum",
    categoryId: "transport",
    description: "Taxi och skärgårdsresor dygnet runt.",
    phone: "0525-435 67",
    email: "boka@kusttaxi.se",
    website: "www.kusttaxi.se",
    address: "Centralgatan 3, Tanumshede",
    initials: "KT",
    boosted: false,
    featured: false,
    rating: 4.7,
    reviewCount: 44,
  },
  {
    id: "18",
    name: "Västkusten Web",
    categoryId: "it",
    description: "Webbyrå specialiserad på lokala företag.",
    phone: "0525-546 78",
    email: "projekt@vastkustenweb.se",
    website: "www.vastkustenweb.se",
    address: "Teknikvägen 6, Tanumshede",
    initials: "VW",
    boosted: true,
    featured: false,
    rating: 4.9,
    reviewCount: 23,
  },
  {
    id: "19",
    name: "Tanum IT-Support",
    categoryId: "it",
    description: "PC-support, nätverkslösningar och IT-säkerhet.",
    phone: "0525-657 89",
    email: "support@tanumit.se",
    address: "Storgatan 22, Tanumshede",
    initials: "TI",
    boosted: false,
    featured: false,
    rating: 4.5,
    reviewCount: 31,
  },
  {
    id: "20",
    name: "Kustmäklaren",
    categoryId: "fastighet",
    description: "Fastighetsmäklare med djup lokalkännedom om Bohuskusten.",
    phone: "0525-768 90",
    email: "info@kustmaklaren.se",
    website: "www.kustmaklaren.se",
    address: "Strandvägen 1, Grebbestad",
    initials: "KM",
    boosted: false,
    featured: false,
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: "21",
    name: "Tanum Förvaltning",
    categoryId: "fastighet",
    description: "Fastighetsförvaltning och teknisk förvaltning.",
    phone: "0525-879 01",
    email: "kontakt@tanumforvaltning.se",
    address: "Centralgatan 7, Tanumshede",
    initials: "TF",
    boosted: false,
    featured: false,
    rating: 4.4,
    reviewCount: 16,
  },
  {
    id: "22",
    name: "Bohusleden Äventyr",
    categoryId: "turism",
    description: "Guidade kajakturerna, klättring och vandring längs Bohusleden.",
    phone: "0525-980 23",
    email: "boka@bohusledenventyr.se",
    website: "www.bohusledeventyr.se",
    address: "Naturvägen 1, Fjällbacka",
    initials: "BÄ",
    boosted: true,
    featured: false,
    rating: 5.0,
    reviewCount: 67,
  },
  {
    id: "23",
    name: "Kosterfjordens Båtcharter",
    categoryId: "turism",
    description: "Hyr vår 32-fots segelbåt med eller utan skipper.",
    phone: "0525-091 34",
    email: "charter@kosterfjorden.se",
    address: "Gästhamnen, Hamburgsund",
    initials: "KB",
    boosted: false,
    featured: false,
    rating: 4.9,
    reviewCount: 41,
  },
  {
    id: "24",
    name: "Tanums Vandrarhem",
    categoryId: "turism",
    description: "Välkomnande vandrarhem mitt i Tanumshede. Nära hällristningarna.",
    phone: "0525-102 45",
    email: "bokning@tanumsvandrarhem.se",
    website: "www.tanumsvandrarhem.se",
    address: "Hällristningsvägen 3, Tanumshede",
    initials: "TV",
    boosted: false,
    featured: false,
    rating: 4.6,
    reviewCount: 88,
  },
];

// Helper used by components when data is passed as props
export function getCategory(categories: Category[], id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}
